# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Diff Action
        # You may pin to the exact commit or the version.
        # uses: technote-space/get-diff-action@f6209c2e93be02d3c2b16956920a47203b3e1bcf
      - uses: technote-space/get-diff-action@v4
        with:
          CHECK_ONLY_COMMIT_WHEN_DRAFT: true 
  print:
    runs-on: ubuntu-latest
    name: echo
    steps:
    - name: print
      run: |
        echo ${{env.GIT_DIFF}}
