on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: test
        run: echo "++++++++++++"
      - name: test diff
        id: git_diff
        uses: ./ # Uses an action in the root directory
      - name: get output
        run: echo "test ${{ steps.git_diff.outputs.trigger }}"